### ISSUE TITLE
Equipment view not sending Authorization header

### ISSUE THREAD

**Issue by mt-code** [e-o-f/equipment-rental#1]
When accessing the equipment view on a newly created user account, multiple requests attempt to retrieve the equipment data without the Authorization header being set. Sometimes 3 unauthorised requests will be sent, other times it can be 20+ times before the Authorization header is sent.

[Click here to preview bug](https://www.dropbox.com/s/ib5mq390qfam11u/equipment-unauth-demo.webm?dl=0)

## Expected Behavior
The authorization header should be set on all authenticated requests, allowing the equipment to be loaded correctly on the first request.

## Current Behavior
It appears the Authorization header is not set on the initial requests to retrieve equipment data, this causes the dashboard to fall into a request loop which makes the equipment table flicker and sending repeating requests. Eventually the Authorization is set which retrieves and displays the data correctly.

## Steps to Reproduce

1. Create a new user account and log in as this user
2. Navigate to the Equipment view

**Comment by GeraldHost** [comment]
Nice spot! This has been fixed here 8e3576fa0673a08561b053517bd1a03e03ca39c9
